# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 18:34
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('second_name', models.CharField(default=None, max_length=30)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default=None, max_length=10)),
                ('email_address', models.EmailField(default=None, max_length=70, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', message='Invalid e-mail address entered')])),
                ('phone_number', models.CharField(default=None, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone Number must be entered        in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date', models.DateField(default=datetime.date.today)),
                ('source', models.CharField(default=None, max_length=50)),
                ('specification_source', models.TextField(blank=True, null=True)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('second_name', models.CharField(blank=True, default=None, max_length=30)),
                ('email_address', models.EmailField(default=None, max_length=70, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', message='Invalid e-mail address entered')])),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone Number must be entered        in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('message', models.TextField(default=None)),
                ('date_entry', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='book_appointment',
        ),
    ]
